import 'package:flutter/material.dart';

enum MvpScreenKind { overview, list, detail, form, success, warning, privacy }

class MvpScreenSpec {
  const MvpScreenSpec({
    required this.id,
    required this.path,
    required this.area,
    required this.title,
    required this.subtitle,
    required this.icon,
    required this.kind,
    this.primaryLabel,
    this.primaryPath,
    this.secondaryLabel,
    this.secondaryPath,
    this.items = const [],
    this.note,
  });

  final String id;
  final String path;
  final String area;
  final String title;
  final String subtitle;
  final IconData icon;
  final MvpScreenKind kind;
  final String? primaryLabel;
  final String? primaryPath;
  final String? secondaryLabel;
  final String? secondaryPath;
  final List<String> items;
  final String? note;
}

/// Complete route-level interface inventory for the tenant-first MVP.
/// Related micro-steps (pickers, validation and confirmations) are composed by
/// the screen renderer so every entry remains navigable in the prototype.
const mvpScreenCatalog = <MvpScreenSpec>[
  MvpScreenSpec(id:'G01',path:'/notifications',area:'Global',title:'Notifications',subtitle:'Updates that need your attention, in one calm feed.',icon:Icons.notifications_outlined,kind:MvpScreenKind.list,primaryLabel:'Notification settings',primaryPath:'/notification-settings',items:['Council tax is due in 3 days|Money · Today','Alex accepted your invitation|Household · Yesterday','Move-in evidence was locked|Vault · 14 August']),
  MvpScreenSpec(id:'G02',path:'/notification-settings',area:'Global',title:'Notification settings',subtitle:'Choose useful reminders without creating noise.',icon:Icons.tune_rounded,kind:MvpScreenKind.form,primaryLabel:'Save preferences',primaryPath:'/settings-saved',items:['Rent and recurring payments|On','Expenses and settlements|On','Household changes|On','Documents and evidence|Off']),
  MvpScreenSpec(id:'G03',path:'/global-search',area:'Global',title:'Search Housely',subtitle:'Find people, payments, documents and belongings.',icon:Icons.search_rounded,kind:MvpScreenKind.list,items:['Council tax|Recurring payment','Tenancy agreement|Shared document','Living room sofa|Shared item','Alex Morgan|Named tenant']),
  MvpScreenSpec(id:'G04',path:'/offline',area:'Global',title:'You are offline',subtitle:'Your saved information is still available. Changes will sync when you reconnect.',icon:Icons.cloud_off_outlined,kind:MvpScreenKind.warning,primaryLabel:'Try again',primaryPath:'/home-preview',items:['Cached home overview','Saved documents','Recorded belongings']),
  MvpScreenSpec(id:'G05',path:'/settings-saved',area:'Global',title:'Preferences saved',subtitle:'Your Housely experience has been updated.',icon:Icons.check_circle_outline_rounded,kind:MvpScreenKind.success,primaryLabel:'Done',primaryPath:'/you'),

  MvpScreenSpec(id:'M01',path:'/household-overview',area:'Household',title:'Household',subtitle:'People connected to George Street Flat.',icon:Icons.people_outline_rounded,kind:MvpScreenKind.overview,primaryLabel:'Invite someone',primaryPath:'/invite-person-type',items:['Muhammad Shaheer|You · Named tenant · Home admin','Alex Morgan|Named on tenancy · Not joined','Meera Thomas|Named on tenancy · Not joined','Maya Jones|Temporary resident · Until 30 September']),
  MvpScreenSpec(id:'M02',path:'/invite-person-type',area:'Household',title:'Who are you inviting?',subtitle:'The person type controls what they can access.',icon:Icons.person_add_alt_1_outlined,kind:MvpScreenKind.list,items:['Named tenant|Equal Home admin permissions','Household member|Lives here but is not named on the tenancy','Temporary resident|Time-limited household access'],note:'A person named on the tenancy is never silently given access. They must accept and confirm their identity.'),
  MvpScreenSpec(id:'M03',path:'/invite-person',area:'Household',title:'Invite to your Home',subtitle:'Add their details and choose the right relationship.',icon:Icons.mail_outline_rounded,kind:MvpScreenKind.form,primaryLabel:'Review invitation',primaryPath:'/review-invitation',items:['Full name|Alex Morgan','Email or mobile|alex@example.com','Person type|Named tenant','Access|Home, shared Vault and tenancy records']),
  MvpScreenSpec(id:'M04',path:'/review-invitation',area:'Household',title:'Review invitation',subtitle:'Check the person and access before sending.',icon:Icons.fact_check_outlined,kind:MvpScreenKind.detail,primaryLabel:'Send invitation',primaryPath:'/invitation-sent',secondaryLabel:'Edit details',secondaryPath:'/invite-person',items:['Alex Morgan|Named tenant','Home|George Street Flat','Access|Shared Home and tenancy records','Private areas|Not shared']),
  MvpScreenSpec(id:'M05',path:'/invitation-sent',area:'Household',title:'Invitation sent',subtitle:'Alex can now confirm their identity and join the Home.',icon:Icons.mark_email_read_outlined,kind:MvpScreenKind.success,primaryLabel:'Back to Household',primaryPath:'/household-overview',secondaryLabel:'Share link',secondaryPath:'/share-invitation'),
  MvpScreenSpec(id:'M06',path:'/share-invitation',area:'Household',title:'Share invitation',subtitle:'Send this secure link directly to Alex.',icon:Icons.ios_share_outlined,kind:MvpScreenKind.detail,primaryLabel:'Copy secure link',primaryPath:'/household-overview',items:['Invitation code|HOUSE-84Q2','Expires|29 August 2026','For|Alex Morgan only']),
  MvpScreenSpec(id:'M07',path:'/person-detail',area:'Household',title:'Alex Morgan',subtitle:'Named on tenancy · Not joined',icon:Icons.person_outline_rounded,kind:MvpScreenKind.detail,primaryLabel:'Resend invitation',primaryPath:'/invitation-sent',secondaryLabel:'Manage record',secondaryPath:'/member-permissions',items:['Legal relationship|Named tenant','App status|Not joined','Invitation|Sent 18 August','Private Split|No access']),
  MvpScreenSpec(id:'M08',path:'/member-permissions',area:'Household',title:'Member access',subtitle:'Only share what this person needs.',icon:Icons.admin_panel_settings_outlined,kind:MvpScreenKind.form,primaryLabel:'Save access',primaryPath:'/settings-saved',items:['Household overview|Allowed','Shared documents|Allowed','Shared inventory|Allowed','Private expenses|Never shared']),
  MvpScreenSpec(id:'M09',path:'/temporary-stay',area:'Household',title:'Temporary stay',subtitle:'Maya can access selected household areas until 30 September.',icon:Icons.event_outlined,kind:MvpScreenKind.detail,primaryLabel:'Extend stay',primaryPath:'/extend-stay',secondaryLabel:'End stay',secondaryPath:'/end-stay',items:['Started|12 August 2026','Ends|30 September 2026','Split access|Guest contributions only','Vault access|Two shared documents']),
  MvpScreenSpec(id:'M10',path:'/extend-stay',area:'Household',title:'Extend temporary stay',subtitle:'Choose a new end date. Existing privacy settings remain unchanged.',icon:Icons.date_range_outlined,kind:MvpScreenKind.form,primaryLabel:'Review extension',primaryPath:'/temporary-stay',items:['Current end date|30 September 2026','New end date|31 October 2026']),
  MvpScreenSpec(id:'M11',path:'/end-stay',area:'Household',title:'End temporary stay?',subtitle:'Maya will immediately lose household access. Their private records remain theirs.',icon:Icons.person_remove_outlined,kind:MvpScreenKind.warning,primaryLabel:'End stay',primaryPath:'/household-overview',secondaryLabel:'Keep access',secondaryPath:'/temporary-stay'),
  MvpScreenSpec(id:'M12',path:'/leave-home',area:'Household',title:'Leave this Home?',subtitle:'Resolve open balances and save anything you need first.',icon:Icons.logout_rounded,kind:MvpScreenKind.warning,primaryLabel:'Review what remains',primaryPath:'/move-out-overview',secondaryLabel:'Not now',secondaryPath:'/you',items:['Open balance|£42.50 owed','Personal documents|4 files','Owned belongings|3 items']),

  MvpScreenSpec(id:'S01',path:'/expense-history',area:'Split',title:'Expense history',subtitle:'A private record of household spending.',icon:Icons.receipt_long_outlined,kind:MvpScreenKind.list,primaryLabel:'Add expense',primaryPath:'/add-expense',items:['Council tax|£165.00 · You paid','Weekly shop|£64.20 · Alex paid','Broadband|£32.00 · You paid','Cleaning supplies|£18.60 · Meera paid']),
  MvpScreenSpec(id:'S02',path:'/balance-detail',area:'Split',title:'Your balance',subtitle:'You owe £42.50 across two people.',icon:Icons.account_balance_wallet_outlined,kind:MvpScreenKind.overview,primaryLabel:'Record settlement',primaryPath:'/record-settlement',items:['Alex Morgan|You owe £30.00','Meera Thomas|You owe £12.50','Muhammad Shaheer|You are owed £18.20']),
  MvpScreenSpec(id:'S03',path:'/split-groups',area:'Split',title:'Split groups',subtitle:'Only participating members can see a private group.',icon:Icons.group_work_outlined,kind:MvpScreenKind.list,primaryLabel:'Create private group',primaryPath:'/create-split-group',items:['George Street Flat|3 members · Household','Weekend groceries|4 members · Private','Edinburgh trip|5 members · Private']),
  MvpScreenSpec(id:'S04',path:'/create-split-group',area:'Split',title:'Create private group',subtitle:'Create a separate space for selected people and expenses.',icon:Icons.group_add_outlined,kind:MvpScreenKind.form,primaryLabel:'Create group',primaryPath:'/split-groups',items:['Group name|Weekend groceries','Members|You, Alex + 2','Visibility|Members only']),
  MvpScreenSpec(id:'S05',path:'/settlement-history',area:'Split',title:'Settlement history',subtitle:'Manually recorded payments. Housely never moves money.',icon:Icons.history_rounded,kind:MvpScreenKind.list,items:['Alex paid you|£45.00 · 12 August','You paid Meera|£21.50 · 3 August','Rent share recorded|£425.00 · 1 August']),
  MvpScreenSpec(id:'S06',path:'/recurring-payments',area:'Split',title:'Recurring payments',subtitle:'See what repeats and what is coming next.',icon:Icons.event_repeat_outlined,kind:MvpScreenKind.list,primaryLabel:'Add recurring payment',primaryPath:'/add-recurring-payment',items:['Rent|£850.00 · Monthly · 1st','Council tax|£165.00 · Monthly · 20th','Broadband|£32.00 · Monthly · 24th','Energy|Variable · Monthly · 28th']),
  MvpScreenSpec(id:'S07',path:'/add-recurring-payment',area:'Split',title:'Add recurring payment',subtitle:'Create a reminder and split. No money moves automatically.',icon:Icons.add_card_outlined,kind:MvpScreenKind.form,primaryLabel:'Review payment',primaryPath:'/recurring-payment-detail',items:['Name|Council tax','Amount|£165.00','Frequency|Monthly','Next due|20 September','Split between|3 people']),
  MvpScreenSpec(id:'S08',path:'/recurring-payment-detail',area:'Split',title:'Council tax',subtitle:'Monthly household commitment.',icon:Icons.calendar_month_outlined,kind:MvpScreenKind.detail,primaryLabel:'Mark September as paid',primaryPath:'/settings-saved',secondaryLabel:'Edit schedule',secondaryPath:'/add-recurring-payment',items:['Amount|£165.00','Next due|20 September','Your share|£55.00','Status|Due in 29 days']),

  MvpScreenSpec(id:'V01',path:'/vault-folders',area:'Vault',title:'Vault folders',subtitle:'Personal, household and tenancy records stay clearly separated.',icon:Icons.folder_outlined,kind:MvpScreenKind.list,primaryLabel:'Upload document',primaryPath:'/upload-document',items:['My documents|4 private files','Household|3 files shared with members','Tenancy|2 files shared with named tenants','Move-in evidence|Locked · 18 August']),
  MvpScreenSpec(id:'V02',path:'/document-viewer',area:'Vault',title:'Tenancy agreement',subtitle:'Shared with named tenants.',icon:Icons.description_outlined,kind:MvpScreenKind.detail,primaryLabel:'View document',primaryPath:'/document-detail',items:['Uploaded|17 August 2026','File|Tenancy-agreement.pdf','Size|2.4 MB','Access|Named tenants']),
  MvpScreenSpec(id:'V03',path:'/document-privacy',area:'Vault',title:'Who can see this?',subtitle:'Documents stay private unless you explicitly share them.',icon:Icons.lock_outline_rounded,kind:MvpScreenKind.form,primaryLabel:'Save privacy',primaryPath:'/settings-saved',items:['Only me|Private','Household|All current members','Named tenants|Legal tenants only','Selected people|Choose individually']),
  MvpScreenSpec(id:'V04',path:'/deposit-rooms',area:'Move-in protection',title:'Move-in evidence',subtitle:'Capture each room, then lock everything with a timestamp.',icon:Icons.shield_outlined,kind:MvpScreenKind.overview,primaryLabel:'Continue walkthrough',primaryPath:'/capture-evidence',items:['Living room|8 photos · Complete','Kitchen|6 photos · Complete','Bedroom|3 photos · In progress','Bathroom|Not started']),
  MvpScreenSpec(id:'V05',path:'/capture-evidence',area:'Move-in protection',title:'Bedroom condition',subtitle:'Capture wide views first, then any existing damage.',icon:Icons.photo_camera_outlined,kind:MvpScreenKind.form,primaryLabel:'Review room',primaryPath:'/review-evidence',items:['Wide room view|Added','Walls and ceiling|Add photo','Flooring|Add photo','Existing damage|Add detail']),
  MvpScreenSpec(id:'V06',path:'/review-evidence',area:'Move-in protection',title:'Review evidence',subtitle:'Check every file before locking. Locked evidence cannot be edited.',icon:Icons.fact_check_outlined,kind:MvpScreenKind.detail,primaryLabel:'Lock with timestamp',primaryPath:'/evidence-locked',secondaryLabel:'Keep editing',secondaryPath:'/deposit-rooms',items:['Rooms|4 of 4 complete','Photos|28','Videos|2','Notes|6']),
  MvpScreenSpec(id:'V07',path:'/evidence-locked',area:'Move-in protection',title:'Evidence protected',subtitle:'Your move-in record is locked and timestamped.',icon:Icons.verified_user_outlined,kind:MvpScreenKind.success,primaryLabel:'View protected record',primaryPath:'/locked-evidence',items:['Locked|22 August 2026 · 14:32','Reference|HLY-EDN-4830','Files|30 protected']),
  MvpScreenSpec(id:'V08',path:'/locked-evidence',area:'Move-in protection',title:'Protected record',subtitle:'Read-only evidence captured when you moved in.',icon:Icons.lock_outline_rounded,kind:MvpScreenKind.detail,primaryLabel:'Export evidence pack',primaryPath:'/export-ready',items:['Living room|8 photos','Kitchen|6 photos','Bedroom|7 photos','Bathroom|7 photos','Record integrity|Verified']),
  MvpScreenSpec(id:'V09',path:'/export-ready',area:'Vault',title:'Export ready',subtitle:'Your evidence pack is ready to save or share.',icon:Icons.download_done_rounded,kind:MvpScreenKind.success,primaryLabel:'Done',primaryPath:'/vault'),

  MvpScreenSpec(id:'I01',path:'/inventory-search',area:'Stuff',title:'Find an item',subtitle:'Search by name, owner, room or warranty.',icon:Icons.search_rounded,kind:MvpScreenKind.list,items:['Living room sofa|Shared · Living room','Air fryer|Yours · Kitchen','Desk chair|Alex · Bedroom','Vacuum cleaner|Household · Hall cupboard']),
  MvpScreenSpec(id:'I02',path:'/scan-item',area:'Stuff',title:'Scan barcode',subtitle:'Place the barcode inside the frame or add the item manually.',icon:Icons.qr_code_scanner_rounded,kind:MvpScreenKind.form,primaryLabel:'Enter manually',primaryPath:'/add-item',items:['Camera access|Ready','Barcode|Waiting to scan']),
  MvpScreenSpec(id:'I03',path:'/warranty-detail',area:'Stuff',title:'Sofa warranty',subtitle:'Coverage ends on 14 October 2026.',icon:Icons.verified_outlined,kind:MvpScreenKind.detail,primaryLabel:'View receipt',primaryPath:'/document-viewer',items:['Retailer|Made.com','Purchased|14 October 2024','Coverage|2 years','Owner|You and Alex']),
  MvpScreenSpec(id:'I04',path:'/transfer-ownership',area:'Stuff',title:'Transfer ownership',subtitle:'The current ownership will remain in the item history.',icon:Icons.swap_horiz_rounded,kind:MvpScreenKind.form,primaryLabel:'Review transfer',primaryPath:'/transfer-review',items:['Item|Living room sofa','Current ownership|You 50% · Alex 50%','Transfer to|Alex Morgan','Effective date|Today']),
  MvpScreenSpec(id:'I05',path:'/transfer-review',area:'Stuff',title:'Review ownership change',subtitle:'This creates a permanent ownership-history entry.',icon:Icons.fact_check_outlined,kind:MvpScreenKind.warning,primaryLabel:'Confirm transfer',primaryPath:'/settings-saved',secondaryLabel:'Go back',secondaryPath:'/transfer-ownership'),

  MvpScreenSpec(id:'C01',path:'/changes-overview',area:'Home changes',title:'Home changes',subtitle:'Important updates are reviewed before they affect the household.',icon:Icons.compare_arrows_rounded,kind:MvpScreenKind.overview,primaryLabel:'Propose a change',primaryPath:'/propose-change',items:['Energy contribution|Waiting for 2 approvals','Rent schedule|Applied 1 August','Maya temporary stay|Applied 12 August']),
  MvpScreenSpec(id:'C02',path:'/propose-change',area:'Home changes',title:'Propose a change',subtitle:'Describe what should change and who it affects.',icon:Icons.edit_note_outlined,kind:MvpScreenKind.form,primaryLabel:'Review proposal',primaryPath:'/review-change',items:['Change type|Recurring payment','Current value|£92.00','Proposed value|£108.00','Reason|Latest energy statement']),
  MvpScreenSpec(id:'C03',path:'/review-change',area:'Home changes',title:'Review proposed change',subtitle:'Relevant named tenants must approve this update.',icon:Icons.rule_folder_outlined,kind:MvpScreenKind.detail,primaryLabel:'Submit for approval',primaryPath:'/change-submitted',secondaryLabel:'Edit',secondaryPath:'/propose-change',items:['Energy|£92.00 → £108.00','Starts|1 September','Affected people|3','Approval needed|2 named tenants']),
  MvpScreenSpec(id:'C04',path:'/change-submitted',area:'Home changes',title:'Change submitted',subtitle:'We will notify the relevant people. Nothing changes until approval.',icon:Icons.hourglass_top_rounded,kind:MvpScreenKind.success,primaryLabel:'View change',primaryPath:'/change-detail'),
  MvpScreenSpec(id:'C05',path:'/change-detail',area:'Home changes',title:'Energy contribution',subtitle:'Waiting for 2 approvals.',icon:Icons.bolt_outlined,kind:MvpScreenKind.detail,primaryLabel:'Review and approve',primaryPath:'/approve-change',items:['Proposed by|Muhammad','New amount|£108.00 monthly','Starts|1 September','Evidence|Energy-statement.pdf']),
  MvpScreenSpec(id:'C06',path:'/approve-change',area:'Home changes',title:'Approve this change?',subtitle:'Confirm that you understand the new amount and start date.',icon:Icons.approval_outlined,kind:MvpScreenKind.warning,primaryLabel:'Approve change',primaryPath:'/change-approved',secondaryLabel:'Request correction',secondaryPath:'/request-correction'),
  MvpScreenSpec(id:'C07',path:'/request-correction',area:'Home changes',title:'Request a correction',subtitle:'Explain what needs to be changed before you can approve.',icon:Icons.rate_review_outlined,kind:MvpScreenKind.form,primaryLabel:'Send request',primaryPath:'/changes-overview',items:['Message|Please attach the full statement.']),
  MvpScreenSpec(id:'C08',path:'/change-approved',area:'Home changes',title:'Approval recorded',subtitle:'The proposal will apply after every required approval.',icon:Icons.check_circle_outline_rounded,kind:MvpScreenKind.success,primaryLabel:'Done',primaryPath:'/changes-overview'),

  MvpScreenSpec(id:'T01',path:'/tasks',area:'Tasks',title:'Household tasks',subtitle:'Small responsibilities, clearly owned.',icon:Icons.checklist_rounded,kind:MvpScreenKind.list,primaryLabel:'Add task',primaryPath:'/create-task',items:['Submit meter reading|You · Due today','Take bins out|Alex · Tomorrow','Replace smoke-alarm battery|Meera · Due Friday','Clean shared hallway|Complete']),
  MvpScreenSpec(id:'T02',path:'/create-task',area:'Tasks',title:'Add household task',subtitle:'Give the task one owner and a clear due date.',icon:Icons.add_task_rounded,kind:MvpScreenKind.form,primaryLabel:'Create task',primaryPath:'/task-detail',items:['Task|Submit meter reading','Assigned to|Muhammad','Due|Today','Repeats|Monthly']),
  MvpScreenSpec(id:'T03',path:'/task-detail',area:'Tasks',title:'Submit meter reading',subtitle:'Assigned to you · Due today',icon:Icons.task_alt_rounded,kind:MvpScreenKind.detail,primaryLabel:'Mark complete',primaryPath:'/task-complete',secondaryLabel:'Edit task',secondaryPath:'/create-task',items:['Home|George Street Flat','Repeats|Monthly','Created by|Muhammad','Reminder|6:00 PM']),
  MvpScreenSpec(id:'T04',path:'/task-complete',area:'Tasks',title:'Task completed',subtitle:'The household timeline has been updated.',icon:Icons.check_circle_outline_rounded,kind:MvpScreenKind.success,primaryLabel:'Back to tasks',primaryPath:'/tasks'),

  MvpScreenSpec(id:'L01',path:'/timeline',area:'Timeline',title:'Home timeline',subtitle:'A clear history of shared-home activity.',icon:Icons.history_rounded,kind:MvpScreenKind.list,items:['Rent marked as paid|Money · Today','Move-in evidence locked|Vault · 18 August','Maya joined temporarily|Household · 12 August','Sofa ownership updated|Stuff · 8 August','Council tax added|Money · 1 August']),
  MvpScreenSpec(id:'L02',path:'/activity-detail',area:'Timeline',title:'Rent marked as paid',subtitle:'Recorded today at 09:21.',icon:Icons.check_circle_outline_rounded,kind:MvpScreenKind.detail,items:['Recorded by|Muhammad Shaheer','Amount|£850.00','Period|August 2026','Visibility|Household']),

  MvpScreenSpec(id:'O01',path:'/move-out-overview',area:'Move out',title:'Your move-out',subtitle:'Finish balances, belongings and evidence without losing your records.',icon:Icons.move_up_outlined,kind:MvpScreenKind.overview,primaryLabel:'Continue move-out',primaryPath:'/move-out-checklist',items:['Balances|£42.50 remaining','Recurring payments|3 to review','Belongings|3 owned items','Evidence|Move-in record protected']),
  MvpScreenSpec(id:'O02',path:'/move-out-checklist',area:'Move out',title:'Move-out checklist',subtitle:'Complete each area before leaving the Home.',icon:Icons.fact_check_outlined,kind:MvpScreenKind.list,primaryLabel:'Compare property condition',primaryPath:'/move-out-compare',items:['Settle balances|Action needed','Review recurring payments|Action needed','Resolve item ownership|3 items','Save personal documents|Ready','Compare move-in evidence|Not started']),
  MvpScreenSpec(id:'O03',path:'/move-out-compare',area:'Move out',title:'Compare property condition',subtitle:'Use your locked move-in record as a factual reference.',icon:Icons.compare_outlined,kind:MvpScreenKind.detail,primaryLabel:'Capture current condition',primaryPath:'/move-out-capture',items:['Living room|Move-in evidence ready','Kitchen|Move-in evidence ready','Bedroom|Move-in evidence ready','Bathroom|Move-in evidence ready']),
  MvpScreenSpec(id:'O04',path:'/move-out-capture',area:'Move out',title:'Current condition',subtitle:'Capture the same views you recorded when moving in.',icon:Icons.photo_camera_outlined,kind:MvpScreenKind.form,primaryLabel:'Review comparison',primaryPath:'/move-out-review',items:['Living room|Complete','Kitchen|Complete','Bedroom|In progress','Bathroom|Not started']),
  MvpScreenSpec(id:'O05',path:'/move-out-review',area:'Move out',title:'Review move-out record',subtitle:'Check the comparison before locking it.',icon:Icons.fact_check_outlined,kind:MvpScreenKind.detail,primaryLabel:'Lock move-out record',primaryPath:'/move-out-complete',items:['Rooms|4 compared','New notes|3','Move-in record|Verified','Move-out files|26']),
  MvpScreenSpec(id:'O06',path:'/move-out-complete',area:'Move out',title:'Move-out record protected',subtitle:'Your evidence pack is ready. Deposit return is awaiting an update.',icon:Icons.verified_user_outlined,kind:MvpScreenKind.success,primaryLabel:'View archived Home',primaryPath:'/archived-home'),
  MvpScreenSpec(id:'O07',path:'/archived-home',area:'Move out',title:'George Street Flat',subtitle:'Archived · 22 August 2026',icon:Icons.inventory_2_outlined,kind:MvpScreenKind.detail,primaryLabel:'Export Home record',primaryPath:'/export-ready',items:['Tenancy|17 August 2025 – 22 August 2026','Deposit return|Awaiting update','Evidence|Move-in and move-out protected','Your documents|4 files']),

  MvpScreenSpec(id:'P01',path:'/profile',area:'You',title:'Personal profile',subtitle:'Your identity across Housely Homes.',icon:Icons.person_outline_rounded,kind:MvpScreenKind.detail,primaryLabel:'Edit profile',primaryPath:'/edit-profile',items:['Name|Muhammad Shaheer','Email|shaheer@example.com','Mobile|+44 7700 900000','Status|Verified']),
  MvpScreenSpec(id:'P02',path:'/edit-profile',area:'You',title:'Edit profile',subtitle:'Keep your contact information accurate.',icon:Icons.edit_outlined,kind:MvpScreenKind.form,primaryLabel:'Save changes',primaryPath:'/settings-saved',items:['Full name|Muhammad Shaheer','Email|shaheer@example.com','Mobile|+44 7700 900000']),
  MvpScreenSpec(id:'P03',path:'/your-homes',area:'You',title:'Your Homes',subtitle:'Current, pending and previous Homes.',icon:Icons.home_work_outlined,kind:MvpScreenKind.list,primaryLabel:'Create or join a Home',primaryPath:'/start-choice',items:['George Street Flat|Current · Home admin','Leith Walk|Archived · Member','Marchmont Flat|Invitation pending']),
  MvpScreenSpec(id:'P04',path:'/app-settings',area:'You',title:'App settings',subtitle:'Make Housely work comfortably for you.',icon:Icons.settings_outlined,kind:MvpScreenKind.list,items:['Notifications|Important updates only','Accessibility|System settings','Appearance|Light','Privacy and security|Review','Data and account|Export or delete']),
  MvpScreenSpec(id:'P05',path:'/accessibility-settings',area:'You',title:'Accessibility',subtitle:'Housely follows your device settings and offers extra control.',icon:Icons.accessibility_new_rounded,kind:MvpScreenKind.form,primaryLabel:'Save accessibility settings',primaryPath:'/settings-saved',items:['Larger text|Use device setting','Reduce motion|Off','Increase contrast|Off','Button labels|Always show']),
  MvpScreenSpec(id:'P06',path:'/privacy-centre',area:'You',title:'Privacy centre',subtitle:'See exactly what is private and what is shared.',icon:Icons.privacy_tip_outlined,kind:MvpScreenKind.privacy,primaryLabel:'Review role access',primaryPath:'/role-privacy',items:['Private Split|Only participants','Personal Vault|Only you','Household records|Current household','Tenancy records|Named tenants','Landlord access|No access to private household areas']),
  MvpScreenSpec(id:'P07',path:'/role-privacy',area:'You',title:'Who can see what?',subtitle:'Access depends on role, participation and explicit sharing.',icon:Icons.visibility_outlined,kind:MvpScreenKind.privacy,items:['Home admin|Shared Home and tenancy setup','Member|Shared household areas','Temporary resident|Time-limited selected areas','Outside friend|Participating Split groups only','Landlord|No private household access']),
  MvpScreenSpec(id:'P08',path:'/security',area:'You',title:'Security',subtitle:'Protect your account and review signed-in devices.',icon:Icons.security_outlined,kind:MvpScreenKind.list,items:['Change password|Updated 3 months ago','Biometric lock|Off','Active sessions|2 devices','Sign out everywhere|Security action']),
  MvpScreenSpec(id:'P09',path:'/active-sessions',area:'You',title:'Active sessions',subtitle:'Sign out any device you do not recognise.',icon:Icons.devices_outlined,kind:MvpScreenKind.list,items:['Chrome on Windows|This device · Edinburgh','Housely on iPhone|Last active yesterday']),
  MvpScreenSpec(id:'P10',path:'/data-controls',area:'You',title:'Your data',subtitle:'Export your records or request account deletion.',icon:Icons.data_usage_outlined,kind:MvpScreenKind.list,items:['Export my data|Create a portable copy','Delete my account|Review impact first']),
  MvpScreenSpec(id:'P11',path:'/export-data',area:'You',title:'Export your data',subtitle:'We will prepare a secure copy of information you can access.',icon:Icons.download_outlined,kind:MvpScreenKind.form,primaryLabel:'Request export',primaryPath:'/export-ready',items:['Profile and account|Included','Private Split records|Included','Personal documents|Included','Shared Home records|Where permitted']),
  MvpScreenSpec(id:'P12',path:'/delete-account',area:'You',title:'Delete your account?',subtitle:'This is permanent after the recovery period. Shared household records may be retained without your private data.',icon:Icons.delete_forever_outlined,kind:MvpScreenKind.warning,primaryLabel:'Continue deletion',primaryPath:'/reauthenticate',secondaryLabel:'Keep my account',secondaryPath:'/you'),
  MvpScreenSpec(id:'P13',path:'/reauthenticate',area:'You',title:'Confirm it is you',subtitle:'Re-enter your password before this sensitive action.',icon:Icons.lock_outline_rounded,kind:MvpScreenKind.form,primaryLabel:'Confirm deletion request',primaryPath:'/deletion-requested',items:['Password|••••••••••••']),
  MvpScreenSpec(id:'P14',path:'/deletion-requested',area:'You',title:'Deletion requested',subtitle:'You can cancel the request during the 14-day recovery period.',icon:Icons.schedule_rounded,kind:MvpScreenKind.success,primaryLabel:'Done',primaryPath:'/welcome'),
  MvpScreenSpec(id:'P15',path:'/help',area:'You',title:'Help and support',subtitle:'Quick answers and a clear way to contact us.',icon:Icons.help_outline_rounded,kind:MvpScreenKind.list,primaryLabel:'Report a problem',primaryPath:'/report-problem',items:['Getting started|Create or join a Home','Privacy|Understand access','Splitting expenses|Balances and settlements','Move-in protection|Locked evidence','Account and security|Manage your account']),
  MvpScreenSpec(id:'P16',path:'/report-problem',area:'You',title:'Report a problem',subtitle:'Tell us what happened. Do not include passwords or payment details.',icon:Icons.bug_report_outlined,kind:MvpScreenKind.form,primaryLabel:'Send report',primaryPath:'/problem-sent',items:['Area|Home','What happened|Describe the issue','Screenshot|Optional','Diagnostics|App version only']),
  MvpScreenSpec(id:'P17',path:'/problem-sent',area:'You',title:'Report sent',subtitle:'Thank you. Your reference is HLY-2048.',icon:Icons.check_circle_outline_rounded,kind:MvpScreenKind.success,primaryLabel:'Done',primaryPath:'/you'),
];

